import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  ShoppingCart,
  Briefcase,
  ShoppingBasket,
  Users,
  Package,
  ClipboardList,
  Scale,
  Trash2,
  TrendingUp,
  Truck,
  Wallet,
  BadgeCheck,
  FileText,
  CreditCard,
  ScrollText,
  BarChart3,
  Receipt,
  LineChart,
  Microscope,
  Building2,
  Settings,
} from "lucide-react";

export const navIcons: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  pos: ShoppingCart,
  "cashier-console": Briefcase,
  cart: ShoppingBasket,
  customers: Users,
  inventory: Package,
  "stock-ledger": ClipboardList,
  reconciliation: Scale,
  wastage: Trash2,
  yield: TrendingUp,
  delivery: Truck,
  "daily-closing": Wallet,
  "discount-approvals": BadgeCheck,
  orders: FileText,
  "pending-payments": CreditCard,
  "purchase-orders": ScrollText,
  reports: BarChart3,
  itr: Receipt,
  analytics: LineChart,
  "advanced-analytics": Microscope,
  hq: Building2,
  settings: Settings,
};
