import { PrismaClient } from '@azela-pos/db';
import { startOfDay, endOfDay } from 'date-fns';

const prisma = new PrismaClient();

/**
 * Daily Closing Service
 * Handles automatic daily closing at 8 PM
 * NO DATABASE SCHEMA CHANGES - Uses existing tables only
 */

interface DailyClosingValidation {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

export class DailyClosingService {
  /**
   * Automatically generate daily closing for a store
   * Called by cron job at 8:00 PM daily
   */
  async generateDailyClosing(storeId: string, closingDate: Date): Promise<any> {
    console.log(`[DailyClosing] Starting auto-closing for store ${storeId} on ${closingDate.toDateString()}`);

    try {
      // Check if closing already exists
      const existing = await prisma.dailyClosing.findFirst({
        where: {
          storeId,
          date: {
            gte: startOfDay(closingDate),
            lte: endOfDay(closingDate),
          },
        },
      });

      if (existing) {
        console.log(`[DailyClosing] Closing already exists for ${closingDate.toDateString()}`);
        return { success: false, message: 'Daily closing already exists', data: existing };
      }

      // Calculate all totals from sales
      const summary = await this.calculateDailySummary(storeId, closingDate);

      // Validate before creating
      const validation = this.validateClosing(summary);
      if (!validation.isValid) {
        console.error(`[DailyClosing] Validation failed:`, validation.errors);
        return { success: false, message: 'Validation failed', errors: validation.errors };
      }

      // Get previous day's closing cash as opening cash
      const previousDayStart = new Date(closingDate);
      previousDayStart.setDate(previousDayStart.getDate() - 1);
      const previousDayEnd = new Date(closingDate);
      previousDayEnd.setDate(previousDayEnd.getDate() - 1);
      
      const previousClosing = await prisma.dailyClosing.findFirst({
        where: {
          storeId,
          date: {
            gte: startOfDay(previousDayStart),
            lte: endOfDay(previousDayEnd),
          },
        },
        orderBy: { date: 'desc' },
      });

      const openingCash = previousClosing?.closingCash || 0;
      const closingCash = openingCash + summary.cashSales;

      // Create daily closing
      const dailyClosing = await prisma.dailyClosing.create({
        data: {
          storeId,
          date: startOfDay(closingDate),
          openingCash,
          closingCash,
          cashDifference: 0, // Will be updated when manager verifies
          totalSales: summary.totalSales,
          totalRevenue: summary.totalRevenue,
          totalDiscounts: summary.totalDiscounts,
          totalTax: summary.totalTax,
          totalWeightSoldKg: summary.totalWeightSoldKg,
          totalWastageKg: summary.totalWastageKg,
          cashSales: summary.cashSales,
          cardSales: summary.cardSales,
          upiSales: summary.upiSales,
          creditSales: summary.creditSales,
          onlineSales: summary.onlineSales,
          notes: 'Auto-generated at 8 PM',
          isAutoGenerated: true,
        },
      });

      console.log(`[DailyClosing] Successfully created closing ${dailyClosing.id}`);

      // Check for warnings
      if (validation.warnings.length > 0) {
        console.warn(`[DailyClosing] Warnings:`, validation.warnings);
      }

      return {
        success: true,
        data: dailyClosing,
        warnings: validation.warnings,
      };
    } catch (error) {
      console.error(`[DailyClosing] Failed to generate:`, error);
      throw error;
    }
  }

  /**
   * Calculate daily summary from sales data
   */
  private async calculateDailySummary(storeId: string, date: Date) {
    const startDate = startOfDay(date);
    const endDate = endOfDay(date);

    // Get all sales for the day
    const sales = await prisma.sale.findMany({
      where: {
        storeId,
        createdAt: {
          gte: startDate,
          lte: endDate,
        },
        status: 'PAID',
      },
      include: {
        items: true,
        payments: true,
      },
    });

    // Calculate totals
    const totalSales = sales.length;
    const totalRevenue = sales.reduce((sum, sale) => sum + (sale.grandTotal || 0), 0);
    const totalDiscounts = sales.reduce((sum, sale) => sum + (sale.discountAmount || 0), 0);
    const totalTax = sales.reduce((sum, sale) => sum + (sale.taxAmount || 0), 0);

    // Calculate weight sold
    const totalWeightSoldKg = sales.reduce((sum, sale) => {
      return sum + (sale.items?.reduce((itemSum, item) => {
        return itemSum + (item.qtyKg || 0);
      }, 0) || 0);
    }, 0);

    // Get wastage for the day
    const wastage = await prisma.inventoryLedger.findMany({
      where: {
        storeId,
        type: 'OUT',
        reason: 'WASTAGE',
        createdAt: {
          gte: startDate,
          lte: endDate,
        },
      },
    });

    const totalWastageKg = wastage.reduce((sum, w) => sum + (w.qtyKg || 0), 0);

    // Calculate payment method breakdowns
    let cashSales = 0;
    let cardSales = 0;
    let upiSales = 0;
    let creditSales = 0;
    let onlineSales = 0;

    sales.forEach(sale => {
      sale.payments?.forEach(payment => {
        switch (payment.method) {
          case 'CASH':
            cashSales += payment.amount;
            break;
          case 'CARD':
            cardSales += payment.amount;
            break;
          case 'UPI':
            upiSales += payment.amount;
            break;
          case 'CREDIT':
            creditSales += payment.amount;
            break;
          case 'ONLINE':
            onlineSales += payment.amount;
            break;
        }
      });
    });

    return {
      totalSales,
      totalRevenue,
      totalDiscounts,
      totalTax,
      totalWeightSoldKg,
      totalWastageKg,
      cashSales,
      cardSales,
      upiSales,
      creditSales,
      onlineSales,
    };
  }

  /**
   * Validate closing data before creating
   */
  private validateClosing(summary: any): DailyClosingValidation {
    const errors: string[] = [];
    const warnings: string[] = [];

    // Critical validations
    if (summary.totalRevenue < 0) {
      errors.push('Total revenue cannot be negative');
    }

    if (summary.totalSales === 0) {
      warnings.push('No sales recorded for the day');
    }

    // Warning validations
    if (summary.cashSales > summary.totalRevenue * 0.9) {
      warnings.push('High cash sales percentage (>90%)');
    }

    if (summary.totalWastageKg > summary.totalWeightSoldKg * 0.1) {
      warnings.push('High wastage detected (>10% of sales)');
    }

    if (summary.totalDiscounts > summary.totalRevenue * 0.2) {
      warnings.push('High discount amount (>20% of revenue)');
    }

    return {
      isValid: errors.length === 0,
      errors,
      warnings,
    };
  }

  /**
   * Get stores that need auto-closing
   */
  async getStoresForAutoClosing(): Promise<string[]> {
    const stores = await prisma.store.findMany({
      where: {
        isActive: true,
      },
      select: {
        id: true,
      },
    });

    return stores.map(s => s.id);
  }
}

export const dailyClosingService = new DailyClosingService();

